version: "3.8"
services:
  db:
    image: postgres:15
    env_file: .env
    ports:
      - "3000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  back:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file: .env
    command: ["sh", "-c", "node src/swagger/swagger.js && node src/server.js"]

volumes:
  pgdata:
